#!/bin/bash

# Copyright (C) 2018 Matthew Marting
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

set -e -o pipefail

source liblock.sh
source libsudo.sh

source libtlogger.sh

readonly LOG_LOCK_PATH_EXT='lock'
readonly LOG_LOCK_PATH_BASENAME=`
 `"$BASENAME_DELIMITER$LOG_LOCK_PATH_EXT"
readonly LOG_LOCK_PATH=`
 `"$LOG_PATH_DIRNAME"'/'"$LOG_LOCK_PATH_BASENAME"

get_the_latest_log_version() {
  tlogger::get_the_log_versions_descending | head --lines=1
}

get_the_next_log_version() {
  echo "$(( $(get_the_latest_log_version) + 1 ))"
}

get_the_next_log_path() {
  tlogger::get_log_path "$(get_the_next_log_version)"
}

main() {
  sudo::the_home_is_the_user_home_or_die
  install --directory -- "$LOG_PATH_DIRNAME"
  lock::make_lock "$LOG_LOCK_PATH"

  if [[ -e $LOG_PATH ]]; then
    local -r log_path="$(get_the_next_log_path)"
  else
    local -r log_path="$LOG_PATH"
  fi

  exec 3>"$log_path"
  lock::free_lock "$LOG_LOCK_PATH"
  local -r command="${*@Q}"
  echo "$command" >&3
  exec 3>&-
    SHELL=/bin/bash \
  script \
    --append \
    --command "$command" \
    --return \
    --quiet \
    -- \
    "$log_path"
}

main "$@"
