#!/bin/bash

# Copyright (C) 2018 Matthew Marting
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

set -e -o pipefail

source libversion.sh

source libtlogger.sh

make_the_next_log() {
  version::make_the_next \
    "$LOG_PATH_DIRNAME" \
    "$LOG_PATH_VERSION_HEAD" \
    "$LOG_PATH_BASENAME" \
    "$LOG_PATH" \
    "$LOG_PATH_VERSION_TAIL" \
    "$LOG_PATH_REGEX"
}

main() {
  local -r log_path="$(make_the_next_log)"
  local -r command="${*@Q}"
  exec 3>>"$log_path"
  echo "$command" >&3
  exec 3>&-
    SHELL=/bin/bash \
  script \
    --append \
    --command "$command" \
    --return \
    --quiet \
    -- \
    "$log_path"
}

main "$@"
