#!/bin/bash

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

set -eo pipefail
unalias -a

_terminal_logger_directory="$HOME/.terminal-logger"
install -d "$_terminal_logger_directory"
{
        _terminal_log_head="$_terminal_logger_directory/terminal."
        _terminal_log="${_terminal_log_head}log"
        _terminal_logs="$_terminal_logger_directory/terminal*.log"
        _terminal_log_pattern='terminal\.([1-9][0-9]*)\.log'
        if [[ -e "$_terminal_log" ]]
        then exec 3> "${_terminal_log_head}$(($({
                for terminal_log in $_terminal_logs
                do
                        if [[ $terminal_log =~ $_terminal_log_pattern ]]
                        then echo "${BASH_REMATCH[1]}"
                        fi
                done
        }|sort -n|tail -n1) + 1)).log"
        else exec 3> "$_terminal_log"
        fi
} 4> "$_terminal_logger_directory/lock"
_date_format='+%Y%m%dT%H%M%S%z'

function format {
        while IFS= read -r x
        do stdbuf -o0 -e0 printf "%s %s%s%s\n" "$(
                stdbuf -o0 -e0 date "$_date_format")" "$1" "$x" "$2"
        done
}

date "$_date_format" >&3
echo "$@" >&3
{ { { { { {
        "$@" 4>&-|tee /dev/stderr 2>&4 4>&-
} 2>&1 >&6|tee /dev/stderr 2>&5 4>&- 5>&- 6>&-
} >&7
} 6>&1|format >&3 4>&- 5>&- 6>&- 7>&-
} 7>&1|format '[1;41m' '[0m' >&3 4>&- 5>&- 6>&- 7>&-
} 4>&1
} 5>&2
