#!/bin/bash

# Copyright (C) 2018 Matthew Marting
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

set -e -o pipefail

source libtlogger.sh

readonly DATE_FORMAT='+%a %b %d %H:%M:%S %Y %z'

get_tty_log_date() {
  local -r tty_log_date_line="$(sed --quiet -- '2p' "$1")"
  echo "${tty_log_date_line#Script started on }"
}

format_tty_log_date() {
  date --date="$(get_tty_log_date "$1")" -- "$DATE_FORMAT"
}

get_tty_log_command() {
  sed --quiet -- '1p' "$1"
}

str_tty_log() {
  echo -e '\E[33mlog '"$1"'\E[m\n'`
         `'Date: '"$(format_tty_log_date "$1")"'\n'`
         `'\n'`
         `'    '"$(get_tty_log_command "$1")"
}

_default_tty_log_exists="$({
[[ -e $TTY_LOG_PATH ]]
echo "$?"
})"

{
for _tty_log_filename_version in $(
    tlogger::get_the_tty_log_versions_descending)
do
  str_tty_log "$(tlogger::get_tty_log_path "$_tty_log_filename_version")"
  [[ ! $_default_tty_log_exists ]] || echo
done

[[ ! $_default_tty_log_exists ]] || str_tty_log "$TTY_LOG_PATH"
}|less -FRX
